# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ef61a90d973634c885330710f6e39174a02e502a50284bd933fdb8078b74adb98d3121cb5fffc491216920cad25f582f0b24da0325a51b9adb271cf066bdb52

test:
  secret_key_base: 5f94956e7f6e0a0c2e28a7f0208a19033c593061b05d11285742c4bd71148c7c3af42f6497f1e27f17ee8a382ef3abcb776c4b854a7b90ac79f95710045d2f04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
